trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '20.x'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(NODE_VERSION)'
    displayName: 'Usar Node.js $(NODE_VERSION)'

  - script: |
      npm install
    displayName: 'Instalar dependências'

  - script: |
      echo "Rodando build ou testes (opcional)"
    displayName: 'Build/Teste (placeholder)'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/ferramenta-backend.zip'
      replaceExistingArchive: true
    displayName: 'Arquivar projeto para deploy'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
    displayName: 'Publicar artefato'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure for Students'
      appName: 'ferramenta-backend-app'
      package: '$(Build.ArtifactStagingDirectory)/ferramenta-backend.zip'
    displayName: 'Deploy no Azure App Service'
